# Generated by Django 5.2.7 on 2025-11-18 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EducationalModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_name",
                    models.CharField(
                        db_index=True,
                        help_text="Module name in Polish (e.g., 'MATEMATYKA')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "is_ai_suggested",
                    models.BooleanField(
                        default=False,
                        help_text="TRUE if AI-suggested, FALSE if predefined",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Educational Module",
                "verbose_name_plural": "Educational Modules",
                "db_table": "educational_modules",
                "ordering": ["module_name"],
            },
        ),
        migrations.CreateModel(
            name="MajorCurriculumReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        db_index=True,
                        help_text="Major section code (e.g., '4', '3')",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "full_text",
                    models.TextField(
                        help_text="Complete Polish text for major section"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Major Curriculum Reference",
                "verbose_name_plural": "Major Curriculum References",
                "db_table": "major_curriculum_references",
                "ordering": ["reference_code"],
            },
        ),
        migrations.CreateModel(
            name="WorkPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        help_text="Weekly theme (optional, e.g., 'Jesień - zbiory')",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Work Plan",
                "verbose_name_plural": "Work Plans",
                "db_table": "work_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CurriculumReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        db_index=True,
                        help_text="Curriculum code (e.g., '4.15', '2.5')",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "full_text",
                    models.TextField(
                        help_text="Complete Polish curriculum requirement text"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "major_reference",
                    models.ForeignKey(
                        help_text="Parent major curriculum section",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="curriculum_references",
                        to="lessonplanner.majorcurriculumreference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curriculum Reference",
                "verbose_name_plural": "Curriculum References",
                "db_table": "curriculum_references",
                "ordering": ["reference_code"],
            },
        ),
        migrations.CreateModel(
            name="WorkPlanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "objectives",
                    models.TextField(
                        blank=True,
                        help_text="Educational objectives (typically 2-3 items)",
                        null=True,
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        help_text="Activity description (required)", max_length=500
                    ),
                ),
                (
                    "is_example",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="TRUE if should be used as LLM training example",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        help_text="Educational module (AI can suggest new modules)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_plan_entries",
                        to="lessonplanner.educationalmodule",
                    ),
                ),
                (
                    "work_plan",
                    models.ForeignKey(
                        help_text="Parent work plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="lessonplanner.workplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Plan Entry",
                "verbose_name_plural": "Work Plan Entries",
                "db_table": "work_plan_entries",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkPlanEntryCurriculumRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "curriculum_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="lessonplanner.curriculumreference",
                    ),
                ),
                (
                    "work_plan_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessonplanner.workplanentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Plan Entry Curriculum Reference",
                "verbose_name_plural": "Work Plan Entry Curriculum References",
                "db_table": "work_plan_entry_curriculum_refs",
                "unique_together": {("work_plan_entry", "curriculum_reference")},
            },
        ),
        migrations.AddField(
            model_name="workplanentry",
            name="curriculum_references",
            field=models.ManyToManyField(
                help_text="Curriculum references for this activity",
                related_name="work_plan_entries",
                through="lessonplanner.WorkPlanEntryCurriculumRef",
                to="lessonplanner.curriculumreference",
            ),
        ),
    ]
