# Generated by Django 5.2.7 on 2025-11-16 16:46

import csv
import os
from django.db import migrations


def load_curriculum_data(apps, schema_editor):
    """
    Populate curriculum references and educational modules from CSV files and PRD data.
    """
    MajorCurriculumReference = apps.get_model('lessonplanner', 'MajorCurriculumReference')
    CurriculumReference = apps.get_model('lessonplanner', 'CurriculumReference')
    EducationalModule = apps.get_model('lessonplanner', 'EducationalModule')
    WorkPlan = apps.get_model('lessonplanner', 'WorkPlan')
    WorkPlanEntry = apps.get_model('lessonplanner', 'WorkPlanEntry')

    # Get the project root directory (go up from webserver/lessonplanner/migrations)
    project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))

    # 1. Load major curriculum references from CSV
    major_refs_file = os.path.join(project_root, 'refs', 'major_curriculum_points.csv')
    major_refs_map = {}  # Maps reference_code to MajorCurriculumReference object

    with open(major_refs_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            major_ref = MajorCurriculumReference.objects.create(
                reference_code=row['curriculum_reference'],
                full_text=row['text']
            )
            major_refs_map[row['curriculum_reference']] = major_ref

    print(f"Created {len(major_refs_map)} major curriculum references")

    # 2. Load curriculum references from CSV
    minor_refs_file = os.path.join(project_root, 'refs', 'minor_curriculum_points.csv')
    curriculum_refs_count = 0

    with open(minor_refs_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            major_ref_code = row['major_curriculum_reference']
            major_ref = major_refs_map.get(major_ref_code)

            if major_ref:
                CurriculumReference.objects.create(
                    reference_code=row['minor_curriculum_reference'],
                    full_text=row['text'],
                    major_reference=major_ref
                )
                curriculum_refs_count += 1

    print(f"Created {curriculum_refs_count} curriculum references")

    # 3. Load educational modules from PRD (Section 9.2)
    educational_modules = [
        'JĘZYK',                # Language
        'MATEMATYKA',           # Mathematics
        'MOTORYKA MAŁA',        # Fine Motor Skills
        'MOTORYKA DUŻA',        # Gross Motor Skills
        'FORMY PLASTYCZNE',     # Artistic Forms
        'MUZYKA',               # Music
        'POZNAWCZE',            # Cognitive
        'WSPÓŁPRACA',           # Cooperation
        'EMOCJE',               # Emotions
        'SPOŁECZNE',            # Social
        'SENSORYKA',            # Sensory
        'ZDROWIE',              # Health
    ]

    for module_name in educational_modules:
        EducationalModule.objects.create(
            module_name=module_name,
            is_ai_suggested=False
        )

    print(f"Created {len(educational_modules)} educational modules")

    # 4. Create example work plans with entries (for LLM training)
    examples = [
        {
            'theme': 'Jesień - zbiory',
            'entries': [
                {
                    'activity': 'Zabawa w sklep z owocami',
                    'module': 'MATEMATYKA',
                    'objectives': 'Dziecko potrafi przeliczać w zakresie 5\nRozpoznaje poznane wcześniej cyfry',
                    'curriculum_refs': ['4.15', '4.18'],
                    'is_example': True
                },
                {
                    'activity': 'Malowanie liści farbami',
                    'module': 'FORMY PLASTYCZNE',
                    'objectives': 'Rozwija koordynację wzrokowo-ruchową\nPosługuje się farbami i pędzlem',
                    'curriculum_refs': ['4.8'],
                    'is_example': True
                },
                {
                    'activity': 'Sortowanie kasztanów według wielkości',
                    'module': 'MATEMATYKA',
                    'objectives': 'Sortuje obiekty według jednej cechy\nRozróżnia wielkości: duży, mały, średni',
                    'curriculum_refs': ['4.12', '4.13'],
                    'is_example': True
                },
            ]
        },
        {
            'theme': 'Zima i święta',
            'entries': [
                {
                    'activity': 'Tworzenie ozdób choinkowych z papieru',
                    'module': 'FORMY PLASTYCZNE',
                    'objectives': 'Dziecko rozwija umiejętności manualne\nWykorzystuje różne materiały plastyczne',
                    'curriculum_refs': ['1.7', '4.8'],
                    'is_example': True
                },
                {
                    'activity': 'Zabawa ruchowa przy piosence "Biegnę do przedszkola"',
                    'module': 'MOTORYKA DUŻA',
                    'objectives': 'Wykonuje różne formy ruchu: bieżne, skoczne\nUczestniczy w zabawach ruchowych i muzycznych',
                    'curriculum_refs': ['1.5', '4.7'],
                    'is_example': True
                },
            ]
        }
    ]

    # Create work plans and entries
    for example in examples:
        work_plan = WorkPlan.objects.create(theme=example['theme'])

        for entry_data in example['entries']:
            # Create the entry
            entry = WorkPlanEntry.objects.create(
                work_plan=work_plan,
                activity=entry_data['activity'],
                module=entry_data['module'],
                objectives=entry_data['objectives'],
                is_example=entry_data['is_example']
            )

            # Link curriculum references
            for ref_code in entry_data['curriculum_refs']:
                try:
                    curr_ref = CurriculumReference.objects.get(reference_code=ref_code)
                    entry.curriculum_references.add(curr_ref)
                except CurriculumReference.DoesNotExist:
                    print(f"Warning: Curriculum reference {ref_code} not found")

    print(f"Created {len(examples)} example work plans with entries")


def reverse_curriculum_data(apps, schema_editor):
    """
    Reverse the data migration by deleting all created objects.
    """
    MajorCurriculumReference = apps.get_model('lessonplanner', 'MajorCurriculumReference')
    EducationalModule = apps.get_model('lessonplanner', 'EducationalModule')
    WorkPlan = apps.get_model('lessonplanner', 'WorkPlan')

    # Delete in reverse order to respect foreign key constraints
    WorkPlan.objects.all().delete()
    EducationalModule.objects.all().delete()
    MajorCurriculumReference.objects.all().delete()  # This cascades to CurriculumReference


class Migration(migrations.Migration):

    dependencies = [
        ("lessonplanner", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_curriculum_data, reverse_curriculum_data),
    ]
