# Generated by Django 5.2.7 on 2025-11-16 16:46

"""
Data migration to populate curriculum references, educational modules, and example work plans.

CSV FILE REQUIREMENTS:
- refs/major_curriculum_points.csv
  Required columns: curriculum_reference, text
  Example: "1","Fizyczny obszar rozwoju dziecka..."

- refs/minor_curriculum_points.csv
  Required columns: major_curriculum_reference, minor_curriculum_reference, text
  Example: "1","1.1","zgłasza potrzeby fizjologiczne..."

These CSV files should be committed to the repository as they contain the official
Polish kindergarten curriculum (Podstawa Programowa).

IDEMPOTENCY:
This migration is idempotent - it can be run multiple times safely.
Uses get_or_create to avoid duplicate key violations.
"""

import csv
import os
from django.db import migrations


def load_curriculum_data(apps, schema_editor):
    """
    Populate curriculum references and educational modules from CSV files and PRD data.

    This migration is idempotent and can be safely re-run.
    """
    MajorCurriculumReference = apps.get_model('lessonplanner', 'MajorCurriculumReference')
    CurriculumReference = apps.get_model('lessonplanner', 'CurriculumReference')
    EducationalModule = apps.get_model('lessonplanner', 'EducationalModule')
    WorkPlan = apps.get_model('lessonplanner', 'WorkPlan')
    WorkPlanEntry = apps.get_model('lessonplanner', 'WorkPlanEntry')

    # Get the project root directory (go up from webserver/lessonplanner/migrations)
    project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))

    # =========================================================================
    # 1. Load major curriculum references from CSV
    # =========================================================================
    major_refs_file = os.path.join(project_root, 'refs', 'major_curriculum_points.csv')

    if not os.path.exists(major_refs_file):
        raise FileNotFoundError(
            f"Required CSV file not found: {major_refs_file}\n"
            f"This file should contain major curriculum reference codes and descriptions.\n"
            f"Expected columns: curriculum_reference, text"
        )

    major_refs_map = {}  # Maps reference_code to MajorCurriculumReference object
    major_created_count = 0

    with open(major_refs_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)

        # Validate CSV columns
        required_columns = {'curriculum_reference', 'text'}
        if not required_columns.issubset(reader.fieldnames or []):
            raise ValueError(
                f"Invalid CSV format in {major_refs_file}\n"
                f"Required columns: {required_columns}\n"
                f"Found columns: {reader.fieldnames}"
            )

        for row in reader:
            major_ref, created = MajorCurriculumReference.objects.get_or_create(
                reference_code=row['curriculum_reference'],
                defaults={'full_text': row['text']}
            )
            major_refs_map[row['curriculum_reference']] = major_ref
            if created:
                major_created_count += 1

    print(f"Major curriculum references: {major_created_count} created, "
          f"{len(major_refs_map) - major_created_count} already existed")

    # =========================================================================
    # 2. Load curriculum references from CSV
    # =========================================================================
    minor_refs_file = os.path.join(project_root, 'refs', 'minor_curriculum_points.csv')

    if not os.path.exists(minor_refs_file):
        raise FileNotFoundError(
            f"Required CSV file not found: {minor_refs_file}\n"
            f"This file should contain detailed curriculum reference codes and descriptions.\n"
            f"Expected columns: major_curriculum_reference, minor_curriculum_reference, text"
        )

    curriculum_created_count = 0
    curriculum_refs_map = {}  # For later reference

    with open(minor_refs_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)

        # Validate CSV columns
        required_columns = {'major_curriculum_reference', 'minor_curriculum_reference', 'text'}
        if not required_columns.issubset(reader.fieldnames or []):
            raise ValueError(
                f"Invalid CSV format in {minor_refs_file}\n"
                f"Required columns: {required_columns}\n"
                f"Found columns: {reader.fieldnames}"
            )

        for row in reader:
            major_ref_code = row['major_curriculum_reference']
            major_ref = major_refs_map.get(major_ref_code)

            if not major_ref:
                raise ValueError(
                    f"Invalid major reference code '{major_ref_code}' in {minor_refs_file}\n"
                    f"This code was not found in {major_refs_file}"
                )

            curr_ref, created = CurriculumReference.objects.get_or_create(
                reference_code=row['minor_curriculum_reference'],
                defaults={
                    'full_text': row['text'],
                    'major_reference': major_ref
                }
            )
            curriculum_refs_map[row['minor_curriculum_reference']] = curr_ref
            if created:
                curriculum_created_count += 1

    print(f"Curriculum references: {curriculum_created_count} created, "
          f"{len(curriculum_refs_map) - curriculum_created_count} already existed")

    # =========================================================================
    # 3. Load educational modules from PRD (Section 9.2)
    # =========================================================================
    educational_modules = [
        'JĘZYK',                # Language
        'MATEMATYKA',           # Mathematics
        'MOTORYKA MAŁA',        # Fine Motor Skills
        'MOTORYKA DUŻA',        # Gross Motor Skills
        'FORMY PLASTYCZNE',     # Artistic Forms
        'MUZYKA',               # Music
        'POZNAWCZE',            # Cognitive
        'WSPÓŁPRACA',           # Cooperation
        'EMOCJE',               # Emotions
        'SPOŁECZNE',            # Social
        'SENSORYKA',            # Sensory
        'ZDROWIE',              # Health
    ]

    modules_created_count = 0
    for module_name in educational_modules:
        _, created = EducationalModule.objects.get_or_create(
            module_name=module_name,
            defaults={'is_ai_suggested': False}
        )
        if created:
            modules_created_count += 1

    print(f"Educational modules: {modules_created_count} created, "
          f"{len(educational_modules) - modules_created_count} already existed")

    # =========================================================================
    # 4. Create example work plans with entries (for LLM training)
    # =========================================================================
    examples = [
        {
            'theme': 'Jesień - zbiory',
            'entries': [
                {
                    'activity': 'Zabawa w sklep z owocami',
                    'module': 'MATEMATYKA',
                    'objectives': 'Dziecko potrafi przeliczać w zakresie 5\nRozpoznaje poznane wcześniej cyfry',
                    'curriculum_refs': ['4.15', '4.18'],
                    'is_example': True
                },
                {
                    'activity': 'Malowanie liści farbami',
                    'module': 'FORMY PLASTYCZNE',
                    'objectives': 'Rozwija koordynację wzrokowo-ruchową\nPosługuje się farbami i pędzlem',
                    'curriculum_refs': ['4.8'],
                    'is_example': True
                },
                {
                    'activity': 'Sortowanie kasztanów według wielkości',
                    'module': 'MATEMATYKA',
                    'objectives': 'Sortuje obiekty według jednej cechy\nRozróżnia wielkości: duży, mały, średni',
                    'curriculum_refs': ['4.12', '4.13'],
                    'is_example': True
                },
            ]
        },
        {
            'theme': 'Zima i święta',
            'entries': [
                {
                    'activity': 'Tworzenie ozdób choinkowych z papieru',
                    'module': 'FORMY PLASTYCZNE',
                    'objectives': 'Dziecko rozwija umiejętności manualne\nWykorzystuje różne materiały plastyczne',
                    'curriculum_refs': ['1.7', '4.8'],
                    'is_example': True
                },
                {
                    'activity': 'Zabawa ruchowa przy piosence "Biegnę do przedszkola"',
                    'module': 'MOTORYKA DUŻA',
                    'objectives': 'Wykonuje różne formy ruchu: bieżne, skoczne\nUczestniczy w zabawach ruchowych i muzycznych',
                    'curriculum_refs': ['1.5', '4.7'],
                    'is_example': True
                },
            ]
        }
    ]

    # Collect any data integrity errors
    integrity_errors = []
    plans_created_count = 0
    entries_created_count = 0

    # Create work plans and entries
    for example in examples:
        # Use get_or_create to avoid duplicates if migration re-runs
        work_plan, created = WorkPlan.objects.get_or_create(
            theme=example['theme'],
            defaults={}
        )
        if created:
            plans_created_count += 1

            # Only create entries if the work plan is new
            # (avoids duplicating entries if plan already exists)
            for entry_data in example['entries']:
                # Create the entry
                entry = WorkPlanEntry.objects.create(
                    work_plan=work_plan,
                    activity=entry_data['activity'],
                    module=entry_data['module'],
                    objectives=entry_data['objectives'],
                    is_example=entry_data['is_example']
                )
                entries_created_count += 1

                # Link curriculum references
                for ref_code in entry_data['curriculum_refs']:
                    if ref_code not in curriculum_refs_map:
                        integrity_errors.append(
                            f"Curriculum reference '{ref_code}' not found for activity "
                            f"'{entry_data['activity']}' in theme '{example['theme']}'"
                        )
                    else:
                        entry.curriculum_references.add(curriculum_refs_map[ref_code])

    # If there were any data integrity errors, raise them
    if integrity_errors:
        raise ValueError(
            f"Data integrity issues found:\n" + "\n".join(f"  - {err}" for err in integrity_errors)
        )

    print(f"Example work plans: {plans_created_count} created")
    print(f"Example work plan entries: {entries_created_count} created")


def reverse_curriculum_data(apps, schema_editor):
    """
    Reverse the data migration by deleting all created objects.
    """
    MajorCurriculumReference = apps.get_model('lessonplanner', 'MajorCurriculumReference')
    EducationalModule = apps.get_model('lessonplanner', 'EducationalModule')
    WorkPlan = apps.get_model('lessonplanner', 'WorkPlan')

    # Delete in reverse order to respect foreign key constraints
    WorkPlan.objects.all().delete()
    EducationalModule.objects.all().delete()
    MajorCurriculumReference.objects.all().delete()  # This cascades to CurriculumReference


class Migration(migrations.Migration):

    dependencies = [
        ("lessonplanner", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_curriculum_data, reverse_curriculum_data),
    ]
